; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html
[env:tm4c123-mini-m4]
platform = titiva
platform_packages = toolchain-gccarmnoneeabi
board = lptm4c123gh6pm
framework = libopencm3
board_build.mcu = tm4c123gh6pm
board_build.ldscript = linker.ld
build_flags =
  -mcpu=cortex-m4
  -mthumb
  -mfpu=fpv4-sp-d16
  -mfloat-abi=hard
  -DTARGET_IS_TM4C123
  -I include
; extra_scripts = extra_script.py
; upload_protocol = custom
; upload_command = python3 -m mikroe_uhb write .pio/build/tm4c123-mini-m4/firmware.bin
; monitor_speed = 115200

