[tivaware]
dir = /Users/robchapm/ti/TivaWare_C_Series-2.2.0.295

[env:mini_m4_tiva]
platform = titiva
board = lptm4c123gh6pm
platform_packages = toolchain-gccarmnoneeabi@~1.90201.0

debug_tool = custom
debug_server =
    openocd
    -f
    openocd.cfg

debug_load_mode = always

upload_command = openocd
    -f openocd.cfg
    -c "program {.pio/build/mini_m4_tiva/firmware.elf} verify reset exit"

debug_port = localhost:3333

debug_init_cmds =
    define pio_reset_halt_target
      monitor reset halt
    end
    define pio_reset_run_target
      monitor reset run
    end
    target extended-remote localhost:3333
    monitor halt
    $LOAD_CMDS
    pio_reset_halt_target

upload_protocol = custom

board_debug.jlink.device = TM4C123GH6PM
board_debug.jlink.interface = swd
board_debug.jlink.speed = 4000

board_build.ldscript = linker.ld

build_flags =
    -DPART_TM4C123GH6PM
    -DTARGET_IS_TM4C123_RB1
    -I${tivaware.dir}
    -I${tivaware.dir}/driverlib
    -Isysconfig
    -mfpu=fpv4-sp-d16
    -mfloat-abi=hard
    -mcpu=cortex-m4
    -mthumb
    -L${tivaware.dir}/driverlib/gcc
    -ldriver

build_src_filter = +<*> +<../sysconfig/*.c>
